### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by drakecdv** [kensteph/to-do-list#10]
### No issues found so far, congratulations! 🥳 
Highlights:
- Very clean and organized code.
- Comments explaining and introducing each functionality.
- Good use of modules.

**Comment by elad237** [comment]
Hello @kensteph there is nothing to say then for you to merge your code
## Hightlight:

- [ ] No linters error
- [ ] fellow Html best practice
- [ ] fellow Javascript best practice
![giphy (2)](https://user-images.githubusercontent.com/109294493/214902616-13a6c159-aa3c-435c-ba52-16007f85d26f.gif)

**Comment by kensteph** [comment]
Thank you, guys!
